spring:
  datasource:
    url: jdbc:h2:mem:checkoutdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080